// js/logbrew-angular/index.js
import { ErrorHandler, InjectionToken, Injector, inject } from "@angular/core";
import {
  createTraceparent,
  LogBrewClient,
  parseTraceparent,
  RecordingTransport,
  SdkError
} from "@logbrew/sdk";

const DEFAULT_SDK_NAME = "logbrew-angular";
const DEFAULT_SDK_VERSION = "0.1.0";

export const LOG_BREW_ANGULAR_CONTEXT = new InjectionToken("LogBrew Angular context");

export function createLogBrewAngularClient({
  apiKey = readEnvApiKey(),
  clientKey = readEnvClientKey(),
  sdkName = DEFAULT_SDK_NAME,
  sdkVersion = DEFAULT_SDK_VERSION,
  maxRetries = 2
} = {}) {
  const authKey = clientKey ?? apiKey;
  if (!authKey) {
    throw new SdkError(
      "configuration_error",
      "createLogBrewAngularClient requires clientKey, apiKey, LOGBREW_CLIENT_KEY, or LOGBREW_API_KEY"
    );
  }
  return LogBrewClient.create({ apiKey: authKey, sdkName, sdkVersion, maxRetries });
}

export function createAngularTraceparent({
  randomValues = defaultRandomValues,
  spanId,
  traceFlags = "01",
  traceId
} = {}) {
  return createTraceparent({
    spanId: spanId ?? randomHex(8, randomValues),
    traceFlags,
    traceId: traceId ?? randomHex(16, randomValues)
  });
}

export function createTraceparentFetch({
  fetchImpl = defaultFetch(),
  randomValues = defaultRandomValues,
  traceFlags = "01",
  traceparent,
  traceparentFactory,
  tracePropagationTargets = []
} = {}) {
  if (typeof fetchImpl !== "function") {
    throw new SdkError("configuration_error", "createTraceparentFetch requires fetch");
  }
  if (!Array.isArray(tracePropagationTargets)) {
    throw new SdkError("configuration_error", "tracePropagationTargets must be an array");
  }
  if (traceparentFactory !== undefined && typeof traceparentFactory !== "function") {
    throw new SdkError("configuration_error", "traceparentFactory must be a function");
  }

  return async function tracedFetch(input, init) {
    const url = requestUrl(input);
    if (!shouldPropagateTraceparent(url, tracePropagationTargets)) {
      return init === undefined ? fetchImpl(input) : fetchImpl(input, init);
    }

    const requestInit = init ?? {};
    const nextTraceparent = traceparentForRequest({
      init,
      input,
      randomValues,
      traceFlags,
      traceparent,
      traceparentFactory,
      url
    });
    const nextInit = {
      ...requestInit,
      headers: headersWithTraceparent(requestHeaders(input, requestInit), nextTraceparent)
    };
    return fetchImpl(input, nextInit);
  };
}

export function shouldPropagateTraceparent(url, tracePropagationTargets = []) {
  if (!Array.isArray(tracePropagationTargets)) {
    throw new SdkError("configuration_error", "tracePropagationTargets must be an array");
  }
  return tracePropagationTargets.some((target) => {
    if (typeof target === "string") {
      return url.includes(target);
    }
    if (target instanceof RegExp) {
      target.lastIndex = 0;
      const matched = target.test(url);
      target.lastIndex = 0;
      return matched;
    }
    if (typeof target === "function") {
      return target(url) === true;
    }
    throw new SdkError("configuration_error", "tracePropagationTargets entries must be strings, RegExp values, or functions");
  });
}

export function provideLogBrew(options = {}) {
  const providers = [
    {
      provide: LOG_BREW_ANGULAR_CONTEXT,
      useFactory: () => {
        const injector = inject(Injector);
        const client = resolveClient(options, injector);
        const transport = resolveTransport(options, injector, client);
        return createLogBrewAngularContext(client, transport);
      }
    }
  ];

  if (options.captureErrors !== false) {
    providers.push({
      provide: ErrorHandler,
      useFactory: () => new LogBrewErrorHandler(
        inject(LOG_BREW_ANGULAR_CONTEXT),
        options,
        resolveDelegateErrorHandler(options)
      )
    });
  }

  return providers;
}

export function injectLogBrew() {
  const context = inject(LOG_BREW_ANGULAR_CONTEXT, { optional: true });
  if (!context) {
    throw new SdkError(
      "configuration_error",
      "injectLogBrew requires provideLogBrew() in the Angular provider tree"
    );
  }
  return context;
}

export class LogBrewErrorHandler {
  constructor(context, options = {}, delegate = null) {
    this.context = context;
    this.options = options;
    this.delegate = delegate;
  }

  handleError(error) {
    void captureAngularError(error, this.context, this.options).catch(() => undefined);
    if (this.delegate && typeof this.delegate.handleError === "function") {
      this.delegate.handleError(error);
    }
  }
}

export function createLogBrewAngularContext(client, transport) {
  return {
    client,
    logbrew: client,
    transport,
    previewJson: () => client.previewJson(),
    flush: () => client.flush(transport),
    shutdown: () => client.shutdown(transport)
  };
}

export function createAngularViewEvent(name, {
  now = () => new Date().toISOString(),
  path = "",
  route = "",
  idFactory = defaultViewEventId,
  metadata = {}
} = {}) {
  const viewPath = path || route;
  return {
    id: idFactory(name, viewPath),
    timestamp: now(),
    attributes: {
      message: viewPath ? `Angular view ${name} at ${viewPath}` : `Angular view ${name}`,
      level: "info",
      logger: "angular",
      metadata: {
        ...metadata,
        name,
        path: viewPath
      }
    }
  };
}

export function createAngularErrorEvent(error, context = {}, {
  now = () => new Date().toISOString(),
  idFactory = defaultErrorEventId
} = {}) {
  const message = error instanceof Error ? error.message : String(error);
  const component = context.component ?? "";
  const route = context.route ?? context.path ?? "";
  return {
    id: idFactory(error, context),
    timestamp: now(),
    attributes: {
      title: component ? `${component} failed` : "Angular error",
      level: "error",
      message,
      metadata: {
        component,
        info: context.info ?? "",
        route
      }
    }
  };
}

export async function captureAngularError(error, context, options = {}) {
  const event = typeof options.errorEvent === "function"
    ? options.errorEvent(error, { context })
    : createAngularErrorEvent(error, options, options);

  try {
    context.client.issue(event.id, event.timestamp, event.attributes);
    const response = await context.client.shutdown(context.transport);
    await notifyFlush(options, response, { context });
    return response;
  } catch (captureError) {
    await notifyFailure(options, captureError, { context });
    throw captureError;
  }
}

function resolveClient(options, injector) {
  if (typeof options.client === "function") {
    return options.client({ injector });
  }
  if (options.client) {
    return options.client;
  }
  return createLogBrewAngularClient(options);
}

function resolveTransport(options, injector, client) {
  if (typeof options.transport === "function") {
    return options.transport({ client, injector });
  }
  return options.transport ?? RecordingTransport.alwaysAccept();
}

function resolveDelegateErrorHandler(options) {
  if (typeof options.delegateErrorHandler === "function") {
    return { handleError: options.delegateErrorHandler };
  }
  return options.delegateErrorHandler ?? null;
}

async function notifyFlush(options, response, context) {
  if (typeof options.onFlush === "function") {
    await options.onFlush(response, context);
  }
}

async function notifyFailure(options, error, context) {
  if (typeof options.onCaptureError === "function") {
    await options.onCaptureError(error, context);
  }
}

function defaultViewEventId(name, path) {
  return `evt_angular_view_${slugify(`${name}_${path}`)}`;
}

function defaultErrorEventId(error, context) {
  const message = error instanceof Error ? error.message : String(error);
  return `evt_angular_error_${slugify(`${context.component ?? ""}_${context.route ?? ""}_${message}`)}`;
}

function defaultFetch() {
  return typeof globalThis.fetch === "function" ? globalThis.fetch.bind(globalThis) : undefined;
}

function defaultRandomValues(length) {
  if (!globalThis.crypto || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new SdkError("configuration_error", "createAngularTraceparent requires crypto.getRandomValues or randomValues");
  }
  const bytes = new Uint8Array(length);
  return globalThis.crypto.getRandomValues(bytes);
}

function headersWithTraceparent(headers, traceparent) {
  const nextHeaders = {};
  for (const [key, value] of headerEntries(headers)) {
    if (String(key).toLowerCase() !== "traceparent") {
      nextHeaders[key] = value;
    }
  }
  nextHeaders.traceparent = traceparent;
  return nextHeaders;
}

function headerEntries(headers) {
  if (headers === undefined || headers === null) {
    return [];
  }
  const HeadersConstructor = globalThis.Headers;
  if (typeof HeadersConstructor === "function" && headers instanceof HeadersConstructor) {
    const entries = [];
    headers.forEach((value, key) => {
      entries.push([key, value]);
    });
    return entries;
  }
  if (Array.isArray(headers)) {
    return headers;
  }
  if (typeof headers !== "string" && typeof headers[Symbol.iterator] === "function") {
    return Array.from(headers);
  }
  if (typeof headers === "object") {
    return Object.entries(headers);
  }
  return [];
}

function randomHex(length, randomValues) {
  if (typeof randomValues !== "function") {
    throw new SdkError("configuration_error", "randomValues must be a function");
  }
  const bytes = Array.from(randomValues(length));
  if (bytes.length !== length || bytes.some((value) => !Number.isInteger(value) || value < 0 || value > 255)) {
    throw new SdkError("configuration_error", "randomValues must return byte values for the requested length");
  }
  return bytes.map((value) => value.toString(16).padStart(2, "0")).join("");
}

function readEnvApiKey() {
  return globalThis.process?.env?.LOGBREW_API_KEY;
}

function readEnvClientKey() {
  return globalThis.process?.env?.LOGBREW_CLIENT_KEY;
}

function requestHeaders(input, init) {
  if (init && init.headers !== undefined) {
    return init.headers;
  }
  return input?.headers;
}

function requestUrl(input) {
  if (typeof input === "string") {
    return input;
  }
  const URLConstructor = globalThis.URL;
  if (typeof URLConstructor === "function" && input instanceof URLConstructor) {
    return input.toString();
  }
  if (typeof input?.url === "string") {
    return input.url;
  }
  return String(input);
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "") || "event";
}

function traceparentForRequest({
  init,
  input,
  randomValues,
  traceFlags,
  traceparent,
  traceparentFactory,
  url
}) {
  const nextTraceparent = typeof traceparentFactory === "function"
    ? traceparentFactory({ init, input, url })
    : traceparent ?? createAngularTraceparent({ randomValues, traceFlags });
  parseTraceparent(nextTraceparent);
  return nextTraceparent;
}

export default {
  captureAngularError,
  createAngularErrorEvent,
  createAngularTraceparent,
  createAngularViewEvent,
  createLogBrewAngularClient,
  createLogBrewAngularContext,
  createTraceparentFetch,
  injectLogBrew,
  LogBrewErrorHandler,
  LOG_BREW_ANGULAR_CONTEXT,
  provideLogBrew,
  shouldPropagateTraceparent
};

// js/logbrew-react/index.js
import React from "react";
import {
  createTraceparent,
  LogBrewClient,
  parseTraceparent,
  SdkError
} from "@logbrew/sdk";

const LogBrewContext = React.createContext(null);

export function createLogBrewReactClient({
  apiKey,
  clientKey,
  sdkName = "logbrew-react",
  sdkVersion = "0.1.0",
  maxRetries = 2
}) {
  const authKey = clientKey ?? apiKey;
  if (!authKey) {
    throw new SdkError("configuration_error", "createLogBrewReactClient requires clientKey or apiKey");
  }
  return LogBrewClient.create({ apiKey: authKey, sdkName, sdkVersion, maxRetries });
}

export function createReactTraceparent({
  randomValues = defaultRandomValues,
  spanId,
  traceFlags = "01",
  traceId
} = {}) {
  return createTraceparent({
    spanId: spanId ?? randomHex(8, randomValues),
    traceFlags,
    traceId: traceId ?? randomHex(16, randomValues)
  });
}

export function createTraceparentFetch({
  fetchImpl = defaultFetch(),
  randomValues = defaultRandomValues,
  traceFlags = "01",
  traceparent,
  traceparentFactory,
  tracePropagationTargets = []
} = {}) {
  if (typeof fetchImpl !== "function") {
    throw new SdkError("configuration_error", "createTraceparentFetch requires fetch");
  }
  if (!Array.isArray(tracePropagationTargets)) {
    throw new SdkError("configuration_error", "tracePropagationTargets must be an array");
  }
  if (traceparentFactory !== undefined && typeof traceparentFactory !== "function") {
    throw new SdkError("configuration_error", "traceparentFactory must be a function");
  }

  return async function tracedFetch(input, init) {
    const url = requestUrl(input);
    if (!shouldPropagateTraceparent(url, tracePropagationTargets)) {
      return init === undefined ? fetchImpl(input) : fetchImpl(input, init);
    }

    const requestInit = init ?? {};
    const nextTraceparent = traceparentForRequest({
      init,
      input,
      randomValues,
      traceFlags,
      traceparent,
      traceparentFactory,
      url
    });
    const nextInit = {
      ...requestInit,
      headers: headersWithTraceparent(requestHeaders(input, requestInit), nextTraceparent)
    };
    return fetchImpl(input, nextInit);
  };
}

export function shouldPropagateTraceparent(url, tracePropagationTargets = []) {
  if (!Array.isArray(tracePropagationTargets)) {
    throw new SdkError("configuration_error", "tracePropagationTargets must be an array");
  }
  return tracePropagationTargets.some((target) => {
    if (typeof target === "string") {
      return url.includes(target);
    }
    if (target instanceof RegExp) {
      target.lastIndex = 0;
      const matched = target.test(url);
      target.lastIndex = 0;
      return matched;
    }
    if (typeof target === "function") {
      return target(url) === true;
    }
    throw new SdkError("configuration_error", "tracePropagationTargets entries must be strings, RegExp values, or functions");
  });
}

export function LogBrewProvider({ client, children }) {
  if (!client) {
    throw new SdkError("configuration_error", "LogBrewProvider requires a client");
  }
  return React.createElement(LogBrewContext.Provider, { value: client }, children);
}

export function useLogBrew() {
  const client = React.useContext(LogBrewContext);
  if (!client) {
    throw new SdkError("configuration_error", "useLogBrew must be used inside LogBrewProvider");
  }
  return client;
}

export function useLogBrewActions() {
  const client = useLogBrew();
  return {
    release: client.release.bind(client),
    environment: client.environment.bind(client),
    issue: client.issue.bind(client),
    log: client.log.bind(client),
    span: client.span.bind(client),
    action: client.action.bind(client),
    flush: client.flush.bind(client),
    shutdown: client.shutdown.bind(client),
    previewJson: client.previewJson.bind(client),
    pendingEvents: client.pendingEvents.bind(client),
    captureReactError: (error, options = {}) => captureReactError(client, error, options)
  };
}

export function createReactErrorEvent(error, {
  componentStack,
  id,
  idFactory = defaultErrorEventId,
  includeComponentStack = true,
  includeStack = false,
  level = "error",
  metadata = {},
  now = () => new Date().toISOString(),
  timestamp
} = {}) {
  const details = errorDetails(error, includeStack);
  const eventMetadata = compactMetadata({
    errorName: details.name,
    errorValueType: details.valueType,
    source: "react.error",
    ...(includeComponentStack ? { componentStack } : {}),
    ...(includeStack ? { errorStack: details.stack } : {}),
    ...metadata
  });
  return {
    id: id ?? idFactory({ error, message: details.message }),
    timestamp: timestamp ?? now(),
    attributes: {
      title: `React error: ${details.message}`,
      level,
      message: details.message,
      metadata: eventMetadata
    }
  };
}

export function captureReactError(client, error, options = {}) {
  if (!client) {
    throw new SdkError("configuration_error", "captureReactError requires a client");
  }
  const event = createReactErrorEvent(error, options);
  client.issue(event.id, event.timestamp, event.attributes);
  return event;
}

export class LogBrewErrorBoundary extends React.Component {
  static contextType = LogBrewContext;

  constructor(props) {
    super(props);
    this.state = { error: null, componentStack: "" };
    this.resetError = this.resetError.bind(this);
  }

  static getDerivedStateFromError(error) {
    return { error };
  }

  componentDidCatch(error, info) {
    const componentStack = info?.componentStack ?? "";
    this.setState({ componentStack });
    try {
      const event = captureReactError(this.props.client ?? this.context, error, {
        componentStack,
        id: this.props.id,
        idFactory: this.props.idFactory,
        includeComponentStack: this.props.includeComponentStack,
        includeStack: this.props.includeStack,
        level: this.props.level,
        metadata: this.props.metadata,
        now: this.props.now,
        timestamp: this.props.timestamp
      });
      if (typeof this.props.onError === "function") {
        this.props.onError(error, info, event);
      }
    } catch (captureError) {
      if (typeof this.props.onCaptureError === "function") {
        this.props.onCaptureError(captureError);
      }
      if (this.props.raiseCaptureErrors === true) {
        throw captureError;
      }
    }
  }

  resetError() {
    this.setState({ error: null, componentStack: "" });
  }

  render() {
    if (this.state.error) {
      const fallback = this.props.fallback ?? null;
      if (typeof fallback === "function") {
        return fallback({
          componentStack: this.state.componentStack,
          error: this.state.error,
          resetError: this.resetError
        });
      }
      return fallback;
    }
    return this.props.children;
  }
}

function defaultFetch() {
  return typeof globalThis.fetch === "function" ? globalThis.fetch.bind(globalThis) : undefined;
}

function defaultRandomValues(length) {
  if (!globalThis.crypto || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new SdkError("configuration_error", "createReactTraceparent requires crypto.getRandomValues or randomValues");
  }
  const bytes = new Uint8Array(length);
  return globalThis.crypto.getRandomValues(bytes);
}

function headersWithTraceparent(headers, traceparent) {
  const nextHeaders = {};
  for (const [key, value] of headerEntries(headers)) {
    if (String(key).toLowerCase() !== "traceparent") {
      nextHeaders[key] = value;
    }
  }
  nextHeaders.traceparent = traceparent;
  return nextHeaders;
}

function headerEntries(headers) {
  if (headers === undefined || headers === null) {
    return [];
  }
  const HeadersConstructor = globalThis.Headers;
  if (typeof HeadersConstructor === "function" && headers instanceof HeadersConstructor) {
    const entries = [];
    headers.forEach((value, key) => {
      entries.push([key, value]);
    });
    return entries;
  }
  if (Array.isArray(headers)) {
    return headers;
  }
  if (typeof headers !== "string" && typeof headers[Symbol.iterator] === "function") {
    return Array.from(headers);
  }
  if (typeof headers === "object") {
    return Object.entries(headers);
  }
  return [];
}

function randomHex(length, randomValues) {
  if (typeof randomValues !== "function") {
    throw new SdkError("configuration_error", "randomValues must be a function");
  }
  const bytes = Array.from(randomValues(length));
  if (bytes.length !== length || bytes.some((value) => !Number.isInteger(value) || value < 0 || value > 255)) {
    throw new SdkError("configuration_error", "randomValues must return byte values for the requested length");
  }
  return bytes.map((value) => value.toString(16).padStart(2, "0")).join("");
}

function requestHeaders(input, init) {
  if (init && init.headers !== undefined) {
    return init.headers;
  }
  return input?.headers;
}

function requestUrl(input) {
  if (typeof input === "string") {
    return input;
  }
  const URLConstructor = globalThis.URL;
  if (typeof URLConstructor === "function" && input instanceof URLConstructor) {
    return input.toString();
  }
  if (typeof input?.url === "string") {
    return input.url;
  }
  return String(input);
}

function compactMetadata(metadata) {
  const compacted = {};
  for (const [key, value] of Object.entries(metadata)) {
    if (value === undefined) {
      continue;
    }
    if (typeof value === "string" || typeof value === "number" || typeof value === "boolean" || value === null) {
      compacted[key] = value;
    }
  }
  return compacted;
}

function errorDetails(error, includeStack) {
  const message = errorMessage(error);
  return {
    message,
    name: errorName(error),
    stack: includeStack && typeof error?.stack === "string" ? error.stack : undefined,
    valueType: error === null ? "null" : typeof error
  };
}

function errorName(error) {
  if (error instanceof Error && typeof error.name === "string" && error.name.trim() !== "") {
    return error.name;
  }
  if (typeof error?.name === "string" && error.name.trim() !== "") {
    return error.name;
  }
  return undefined;
}

function errorMessage(error) {
  if (error instanceof Error && typeof error.message === "string" && error.message.trim() !== "") {
    return error.message;
  }
  if (typeof error?.message === "string" && error.message.trim() !== "") {
    return error.message;
  }
  if (typeof error === "string" && error.trim() !== "") {
    return error;
  }
  return String(error ?? "unknown error");
}

function defaultErrorEventId({ message }) {
  return `evt_react_error_${slugify(message)}`;
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "") || "event";
}

function traceparentForRequest({
  init,
  input,
  randomValues,
  traceFlags,
  traceparent,
  traceparentFactory,
  url
}) {
  const nextTraceparent = typeof traceparentFactory === "function"
    ? traceparentFactory({ init, input, url })
    : traceparent ?? createReactTraceparent({ randomValues, traceFlags });
  parseTraceparent(nextTraceparent);
  return nextTraceparent;
}

export default {
  LogBrewErrorBoundary,
  LogBrewProvider,
  captureReactError,
  createLogBrewReactClient,
  createReactErrorEvent,
  createReactTraceparent,
  createTraceparentFetch,
  shouldPropagateTraceparent,
  useLogBrew,
  useLogBrewActions
};
